apiVersion: v1 
kind: Namespace
metadata:
  name: demo-deployment
---
apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
  namespace: demo-deployment
spec:
  completions: 3
  parallelism: 2
  template:
    metadata:
      labels:
        app: example 
    spec:
      containers:
      - name: example
        image: busybox
        command: ["echo",  "Hello, Kubernetes"]
      restartPolicy: Never
