apiVersion: v1
kind: Namespace
metadata:
  name: demo-deployment
---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginx
  labels:
    app: nginx
  namespace: demo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "128m"
          requests:
            memory: "128Mi"
            cpu: "64m"