apiVersion: v1 
kind: Namespace
metadata:
  name: demo-deployment
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: demo-deployment
spec:
  serviceName: "mysql"
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mariadb
        ports:
        - containerPort: 3306
          name: web
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
