apiVersion: v1
kind: Namespace 
metadata:
  name: secretExample
--- 
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: secretExample
type: Opaque
data:
  username: YWRtaW4=  # base64 encoded "admin"
  password: cGFzc3dvcmQ=  # base64 encoded "password"
--- 
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  namespace: secretExample
spec:
  containers:
  - name: my-container
    image: my-image
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 8080
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: example-secret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: example-secret
          key: password
--- 
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  namespace: secretExample
spec:
  containers:
  - name: my-container
    image: my-image
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secret
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: example-secret
